### ISSUE TITLE
recipe?

### ISSUE THREAD

**Issue by bill-auger** [fa7ad/av-caster-aur#1]
reading up on this a bit it seems to me that this AUR business is more complicated than helpful

how does one normally find a package in AUR? are they found only by searching the website?

how does one normally install a package from AUR? so far i've found 3 different ways

is there some CLI or GUI tool for searching and installing these?

```
git clone https://aur.archlinux.org/av-caster.git
cd av-caster
makepkg -sri ./PKGBUILD
```

```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/av-caster.tar.gz
tar xzf av-caster.tar.gz
cd av-caster
makepkg -sri ./PKGBUILD
```

```
wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=av-caster
makepkg -sri ./PKGBUILD
```

noting that none of those offer any convenience over the existing method:

```
wget https://raw.githubusercontent.com/bill-auger/av-caster/master/Builds/Packaging/PKGBUILD
makepkg -sri ./PKGBUILD
```

at first i though perhaps this would allow arch users to find and install av-caster with pacman but it seems this is not the case - if the only way to find av-caster this way is by searching the web and if the only way to install this way is to manually download the PKGBUILD file and compile with makepkg then i do not see any advantage to using the AUR

i mention this because you asked me to note this AUR repo somewhere in the documentation - upon doing so i realized that the instructions would be identical except that it would suggest fetching the PKGBUILD file from a third-party host when that identical PKGBUILD file is available in the same location as the README where the instructions are mentioned - this doesnt seem sensible and i dont know what else i could say about the AUR repo other than that it exists - why would anyone be interested to know that? - i could understand if one method were more convenient than another - for example i could easily build and host a binary package for arch on OBS - that actually would be more convenient but no one has asked for one yet

does AUR make download statistics available so that it can be determined if anyone is making use of it?

**Comment by fa7ad** [comment]
No, to install from the AUR most people use `pacaur` or `yaourt`.

Like:

``` bash
yaourt -S av-caster
```

Or,

``` bash
pacaur -S av-caster
```

That's it.

The advantage is that people don't need to worry about the compilation steps, or manually check for update, or to make sure all the dev dependencies are satisfied. Besides, its the place Arch users tend to look for 3rd party packages. Sort of like having a PPA instead of just DEB files for Ubuntu. :smile: 
Its also like an unofficial convention to have an AUR for arch releases.

Example:
![shot_2016-09-09_062410](https://cloud.githubusercontent.com/assets/7447677/18371496/83bf8dac-7656-11e6-98d6-4eab57c1b32f.jpg)

To make a release to AUR: 
1. I pull from this remote (or some other source)
2. Bump the version/release number on PKGBUILD
3. Update the _.SRCINFO_ file, `makepkg --printsrcinfo > .SRCINFO`
4. Commit
5. Push to the AUR remote

**Comment by bill-auger** [comment]
i meant 'recipe' for the documentation - which commands must a typical user run to install av-caster this way

## so it could say something like this ....

If you are subscribed to the AUR repos you can install AvCaster like:

```
yaourt -S av-caster
```

## or like this?

If you have the yaourt program installed you can install AvCaster like:

```
yaourt -S av-caster
```

## or like this?

If you have the yaourt program installed and you are subscribed to the AUR repos you can install AvCaster like:

```
yaourt -S av-caster
```

**Comment by fa7ad** [comment]
Just link the AUR repo.
or something like,

> # Arch Linux
> 
> Install `av-caster` from the AUR
> or
> Use this [PKGBUILD](#)

**Comment by bill-auger** [comment]
ah yes i see now there are dozens of ways to install AUR packages https://wiki.archlinux.org/index.php/AUR_helpers
